### ISSUE TITLE
Ejercicio 9 Reelaborado: Creación del "Menú Estrella" con Enfoque en Alérgenos usando HTML5 y CSS

### ISSUE THREAD

**Issue by atiribeja04** [atiribeja04/lmsgi-gusteaus#9]
# Ejercicio 9 Reelaborado: Creación del "Menú Estrella" con Enfoque en Alérgenos usando HTML5 y CSS

## Descripción 

El objetivo es Desarrollar una página web para el "Menú Estrella" del restaurante Gusteau's, haciendo énfasis en la presentación de información sobre alérgenos utilizando atributos `data-` en HTML5 y estilos CSS.

## Esqueleto de página del menú HTML

```html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menú Estrella de Gusteau's</title>
    <link rel="stylesheet" href="css/estilos.css">
</head>
<body>
    <header># Ejercicio 1 - Estilos Básicos con Temática de Restaurante Elegante

## Descripción

Este ejercicio tiene como objetivo aplicar estilos básicos al documento HTML del restaurante Gusteau's, incorporando un diseño elegante y acogedor típico de los bistros parisinos.

## Tareas:

- [ ] Configurar el Contenedor General (#contenedor):
  - [ ] Establecer el color de fondo a `#fff8f0` (un tono suave de crema).
  - [x] Definir el tipo de letra como `'Times New Roman', serif`.
  - [x] Ajustar el tamaño del texto a `16px`.

- [ ] Diseñar el Encabezado (div.encabezado):
  - [ ] Utilizar la imagen de cabecera del restaurante como fondo.
  - [ ] Configurar el color del texto a `#5a3e36` (marrón oscuro).
  - [ ] Seleccionar el tipo de letra `'Georgia', serif`.
  - [ ] Establecer el tamaño del texto a `36px`.
  - [ ] Alinear el texto al centro.
  - [ ] Ajustar la altura al tamaño de la imagen de cabecera.

- [ ] Estilizar el Menú de Navegación (div.menu ul li a):
  - [ ] Fijar el color de fondo en `#a77e58` (tono marrón claro).
  - [ ] Definir el color del texto como `#ffffff` (blanco).
  - [ ] Usar el tipo de letra `'Helvetica', sans-serif`.
  - [ ] Establecer el tamaño del texto en `18px`.
  - [ ] Agregar una transición suave al cambiar el color al pasar el mouse a `#8b6f47`.

- [ ] Dar estilo al Contenido Principal (div.contenido):
  - [ ] Configurar el color de fondo a `#fff8f0`.
  - [ ] Definir el color del texto como `#5a3e36`.
  - [ ] Seleccionar el tipo de letra `'Georgia', serif`.
  - [ ] Establecer el tamaño del texto a `18px`.

- [ ] Personalizar la Barra Lateral (div.sidebar):
  - [ ] Establecer el color de fondo en `#ecdcc6` (un tono crema más claro).
  - [ ] Definir el color del texto como `#5a3e36`.
  - [ ] Utilizar el tipo de letra `'Georgia', serif`.
  - [ ] Establecer el tamaño del texto en `18px`.

- [ ] Diseñar el Pie de Página (div.pie):
  - [ ] Fijar el color de fondo en `#a77e58`.
  - [ ] Configurar el color del texto como `#ffffff`.
  - [ ] Seleccionar el tipo de letra `'Helvetica', sans-serif`.
  - [ ] Establecer el tamaño del texto en `16px`.
  - [ ] Alinear el texto al centro.

## Instrucciones Adicionales:

- Asegúrate de que todos los elementos tengan un margen y un padding adecuados para una presentación limpia y elegante.
- Manten una coherencia estilística que refleje la elegancia y sofisticación de un restaurante parisino.

## Referencias:

- Puedes consultar la documentación de CSS en [Mozilla Developer Network (MDN)](https://developer.mozilla.org/es/docs/Web/CSS) para obtener información detallada sobre las propiedades y valores de estilo CSS.
- Aquí tienes una guía sobre [cómo usar selectores en CSS](https://developer.mozilla.org/es/docs/Web/CSS/Cómo_seleccionar_elementos).

¡Buena suerte con el ejercicio! Si tienes alguna pregunta o necesitan ayuda adicional, no dudes en comentar esta issue.
        <h1>Menú Estrella del Restaurante Gusteau's</h1>
    </header>

    <nav>
        <!-- Menú de navegación aquí, si es necesario -->
    </nav>

    <main>
        <section class="menu-estrella">
            <h2>Platos Principales</h2>
            <ul>
                <li data-alergenos="nueces mariscos">Ensalada Mediterránea con Nueces y Gambas</li>
                <li data-alergenos="nueces">Tarta de Chocolate y Nueces</li>
                <li data-alergenos="mariscos">Paella de Mariscos</li>
                <li>Sopa de Verduras</li>
                <!-- Más platos aquí -->
            </ul>

            <h2>Entrantes</h2>
            <ul>
                <!-- Ítems de entrantes aquí -->
            </ul>

            <h2>Postres</h2>
            <ul>
                <!-- Ítems de postres aquí -->
            </ul>
        </section>
    </main>

    <footer>
        <!-- Información del pie de página aquí -->
    </footer>
</body>
</html>
```

## Uso del atributo `data-` en HTML5

- El atributo `data-` en HTML5 se utiliza para almacenar información adicional sobre un elemento, que no está directamente relacionada con la representación o el comportamiento estándar del elemento.
- Es importante porque permite a los desarrolladores web agregar datos personalizados a sus elementos HTML de una manera que es accesible a través de CSS y JavaScript, sin alterar la semántica del documento.
- En este ejercicio, usamos `data-alergenos` para identificar los alérgenos presentes en cada plato, lo que permite una gran flexibilidad para estilizar y manipular estos elementos según sea necesario.

### Estilización del menú

- [ ] Aplicar estilos CSS para crear un diseño visualmente atractivo y coherente con el tema del restaurante.
- [ ] Incluir estilos para encabezados, listas de platos y elementos individuales del menú.

### Manejo de Alérgenos

- [ ] Utilizar los atributos data-alergenos para identificar platos con alérgenos específicos y aplicar estilos distintivos a estos elementos.
- [ ] Para platos con múltiples alérgenos, asegurarse de que el estilo aplicado sea claro y diferenciable.

### Interactividad y detalles de Alergenos

- [ ] Implementar efectos :hover para resaltar los platos al pasar el mouse
- [ ] Usar selectores avanzados en CSS para aplicar estilos basados en los valores de `data-alergenos`.
